image: "ruby:2.4"

cache:
  paths:
    - .bundle
    - vendor/

before_script:
  - apt-get update >/dev/null
  - apt-get install -y locales >/dev/null
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
  - bundle install --jobs $(nproc) --path /cache/bundler

test:
  script:
  - bundle exec rake test

html_proofer:
  allow_failure: yes
  script:
  - bundle exec rake html_proofer


pages:
  script:
  - bundle exec jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
