language: ruby
sudo: false
cache: bundler

branches:
  only:
    - master
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

before_install:
  - bundle update --bundler
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - RUN=html_proofer
    - RUN=test

script: 'script/ci.rb'
