language: ruby
sudo: false
cache: bundler

branches:
  only:
    - master
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jobs:
  include:
    - stage: test
      script: 'script/ci.rb'
      env: RUN=html_proofer
    - stage: test
      script: 'script/ci.rb'
      env: RUN=test
