# For more permalink examples see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title/

include: [".htaccess"]
exclude: [".rvmrc", ".rbenv-version", "Rakefile", "README.md", "Vagrantfile", 'test/', 'script/', 'vendor/']

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Philipp Hansch
author :
  name : Philipp Hansch
  email : hi@phansch.net
  github : phansch
  twitter : phansch

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://phansch.net

sass:
  sass_dir: _sass
  style: :compressed

atom_path : /atom.xml
rss_path : /rss.xml
